### ISSUE TITLE
Changes to the C library do not trigger a rebuild

### ISSUE THREAD

**Issue by egrimley-arm** [parallaxsecond/rust-psa-crypto#35]
If the C code in `psa-crypto-sys/vendor/` is changed then `cargo` does not rebuild it.

A work-around is to run `touch psa-crypto-sys/build.rs` when the C code might have changed.

I think it would be better if `build.rs` found every file (and perhaps every directory) under `vendor/` (there's a crate called `walkdir`) and emitted `cargo:rerun-if-changed=PATH` for each one. (Or you could try to more selective, but persuading `cmake` to tell you which files really matter would probably be too much work.)

**Comment by hug-dev** [comment]
Thanks for the report!

> A work-around is to run touch psa-crypto-sys/build.rs when the C code might have changed.

oh wow I did not know that `touch` could do that! The name of the command now makes more sense 😄 
The `walkdir` idea seems nice! If we do `cargo:rerun-if-changed=vendor`, will it detect any change inside the directory? I would say no by default, but maybe here it will since this is a git repository. I am also wondering if we can target a git file in `.git` (or `.git` itself) to check for any change.
